"""add password reset token to admin_users

Revision ID: 4e27d87fb745
Revises: 9150a53cca7b
Create Date: 2026-08-05 19:55:56.152112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e27d87fb745'
down_revision: Union[str, None] = '9150a53cca7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('password_reset_token_hash', sa.String(length=128), nullable=True))
    op.add_column('admin_users', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'password_reset_expires_at')
    op.drop_column('admin_users', 'password_reset_token_hash')
    # ### end Alembic commands ###
