"""add revoked refresh tokens

Revision ID: 870341e14e93
Revises: c402bd71e630
Create Date: 2026-07-31 15:59:18.575665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870341e14e93'
down_revision: Union[str, None] = 'c402bd71e630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_refresh_tokens_jti'), 'revoked_refresh_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_refresh_tokens_jti'), table_name='revoked_refresh_tokens')
    op.drop_table('revoked_refresh_tokens')
    # ### end Alembic commands ###
