"""admin user hardening: lockout, 2fa secret, invite token

Revision ID: 9150a53cca7b
Revises: 870341e14e93
Create Date: 2026-07-31 20:59:02.009532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9150a53cca7b'
down_revision: Union[str, None] = '870341e14e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('two_factor_secret', sa.String(length=64), nullable=True))
    op.add_column(
        'admin_users',
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('admin_users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('admin_users', sa.Column('invite_token_hash', sa.String(length=128), nullable=True))
    op.add_column('admin_users', sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'invite_expires_at')
    op.drop_column('admin_users', 'invite_token_hash')
    op.drop_column('admin_users', 'locked_until')
    op.drop_column('admin_users', 'failed_login_attempts')
    op.drop_column('admin_users', 'two_factor_secret')
    # ### end Alembic commands ###
